"""Multi-cycle autonomous feedback loop driver.

Wraps ``iteration_loop`` in an outer while-loop that reads the review decision
after each cycle, finds the next-cycle assignment generated by ``next_cycle``,
and re-enters ``iteration_loop`` until a terminal condition is met.
"""

from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Sequence

from scripts.agents.self_evolved_abc.flow.assignment import (
    normalize_flow_assignment_scope,
)


# Review decisions that should keep the loop running.
CONTINUE_DECISIONS = frozenset(
    (
        "ACCEPT_FOR_NEXT_CYCLE",
        "REPAIR_QOR",
        "REPAIR_BUILD",          # legacy / fallback
        "REPAIR_VALIDATION",     # model JSON validation failed
        "REPAIR_PATCH",          # diff didn't apply
        "REPAIR_SMOKE",          # python smoke gate failed
        "REPAIR_COMPILE",        # C compile failed
        "REPAIR_EVALUATION",
        "REJECT_CEC",
    )
)

STUCK_THRESHOLD = 3  # consecutive cycles with the same decision → warn and stop


def parse_args(argv: Sequence[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Run the Flow Agent feedback loop across multiple cycles."
    )
    parser.add_argument("--repo-root", type=Path, default=Path.cwd())
    parser.add_argument(
        "--assignment",
        type=Path,
        default=None,
        help="Explicit starting assignment. Required unless --auto-resume is set.",
    )
    parser.add_argument(
        "--auto-resume",
        action="store_true",
        help=(
            "Automatically find the highest completed cycle (the one with a "
            "review_decision.json) and start from the next cycle.  Existing "
            "cycles are never overwritten.  Falls back to cycle_001 if no "
            "cycles have been run yet."
        ),
    )
    parser.add_argument(
        "--max-cycles",
        type=int,
        default=5,
        help="Maximum number of cycles to run before stopping.",
    )
    parser.add_argument(
        "--build-candidate-binary",
        action="store_true",
        help="Build candidate ABC inside isolated workspace before S5/F7.",
    )
    parser.add_argument("--build-jobs", type=int, default=4)
    parser.add_argument("--build-timeout-seconds", type=float, default=900.0)
    parser.add_argument("--timeout-seconds", type=float, default=300.0)
    return parser.parse_args(argv)


def main(argv: Sequence[str] | None = None) -> int:
    args = parse_args(sys.argv[1:] if argv is None else argv)
    repo_root = args.repo_root.resolve()

    if args.assignment is not None:
        current_assignment = repo_root / args.assignment
    elif args.auto_resume:
        current_assignment = _find_resume_point(repo_root)
    else:
        print("cycle_loop: either --assignment or --auto-resume is required")
        return 2

    champion_cycle: str | None = None
    stuck_count = 0
    last_decision: str | None = None

    for iteration in range(1, args.max_cycles + 1):
        # Derive cycle id from the assignment path: experiments/<cycle>/agents/assignments/<candidate>.json
        cycle_id = current_assignment.parent.parent.parent.name
        next_cycle_id = _increment_cycle_id(cycle_id)

        print(f"\n{'=' * 60}")
        print(f"cycle_loop: iteration {iteration}/{args.max_cycles}  ({cycle_id})")
        print(f"{'=' * 60}\n")

        # Ensure a flow recipe exists (needed by implementation_compare)
        _ensure_flow_recipe(repo_root, cycle_id)

        # Skip if this cycle already has a review decision
        if _review_exists(repo_root, cycle_id):
            print(f"cycle_loop: {cycle_id} already completed — skipping")
            current_assignment = _next_assignment_path(repo_root, next_cycle_id)
            if current_assignment is None:
                print("cycle_loop: stopping — no next assignment after skip")
                break
            continue

        # Run one full iteration
        iter_cmd = _build_iteration_command(
            repo_root=repo_root,
            assignment=current_assignment,
            next_cycle=next_cycle_id,
            build_candidate_binary=args.build_candidate_binary,
            build_jobs=args.build_jobs,
            build_timeout_seconds=args.build_timeout_seconds,
            timeout_seconds=args.timeout_seconds,
        )
        print(f"running: {' '.join(iter_cmd)}")
        completed = subprocess.run(iter_cmd, cwd=repo_root, check=False)

        # Read review decision
        review_path = (
            repo_root
            / "experiments"
            / cycle_id
            / "impl_compare"
            / "comparison"
            / "review_decision.json"
        )
        decision = _read_decision(review_path)
        print(f"cycle_loop: {cycle_id} decision = {decision}")

        if decision == "ACCEPT_FOR_NEXT_CYCLE":
            champion_cycle = cycle_id
            print(f"cycle_loop: new champion = {champion_cycle}")

        # Detect stuck state
        if decision == last_decision:
            stuck_count += 1
        else:
            stuck_count = 0
        last_decision = decision

        if stuck_count >= STUCK_THRESHOLD:
            print(
                f"cycle_loop: stopping — same decision {decision!r} "
                f"for {stuck_count} consecutive cycles"
            )
            break

        if decision not in CONTINUE_DECISIONS:
            print(
                f"cycle_loop: stopping — terminal decision {decision!r}"
            )
            break

        # Find next assignment
        next_assignment = (
            repo_root
            / "experiments"
            / next_cycle_id
            / "agents"
            / "assignments"
            / "candidate_001.json"
        )
        if not next_assignment.is_file():
            print(
                f"cycle_loop: stopping — next assignment not found: "
                f"{next_assignment.relative_to(repo_root)}"
            )
            break

        current_assignment = next_assignment

    print(f"\ncycle_loop: finished.  champion = {champion_cycle or 'none'}")
    return 0


def _build_iteration_command(
    *,
    repo_root: Path,
    assignment: Path,
    next_cycle: str,
    build_candidate_binary: bool,
    build_jobs: int,
    build_timeout_seconds: float,
    timeout_seconds: float,
) -> tuple[str, ...]:
    cmd: list[str] = [
        sys.executable,
        "-B",
        "-m",
        "scripts.agents.self_evolved_abc.flow.iteration_loop",
        "--repo-root",
        str(repo_root),
        "--assignment",
        str(assignment.relative_to(repo_root)),
        "--next-cycle",
        next_cycle,
        "--force-next-assignment",
        "--timeout-seconds",
        f"{timeout_seconds:g}",
    ]
    if build_candidate_binary:
        cmd.extend(
            (
                "--build-candidate-binary",
                "--build-jobs",
                str(max(1, build_jobs)),
                "--build-timeout-seconds",
                f"{build_timeout_seconds:g}",
            )
        )
    return tuple(cmd)


def _read_decision(path: Path) -> str:
    if not path.is_file():
        return "MISSING_REVIEW"
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError):
        return "UNPARSEABLE_REVIEW"
    return str(payload.get("decision", "MISSING_DECISION_FIELD"))


def _ensure_flow_recipe(repo_root: Path, cycle_id: str) -> None:
    """Copy the baseline flow recipe for the current cycle if it doesn't exist."""
    flow_dir = repo_root / "configs" / "flows"
    flow_path = flow_dir / f"{cycle_id}_candidate_001.abc"
    if flow_path.is_file():
        return
    # Find any existing flow recipe to reuse as template
    template = None
    for candidate in sorted(flow_dir.glob("cycle_*_candidate_001.abc")):
        template = candidate
        break
    if template is not None:
        shutil.copy2(template, flow_path)
        print(f"cycle_loop: copied flow recipe {template.name} → {flow_path.name}")
    else:
        print("cycle_loop: warning — no flow recipe template found")


def _find_resume_point(repo_root: Path) -> Path:
    """Find the highest completed cycle and return the next assignment.

    A cycle is considered "completed" if its review_decision.json exists.
    Returns the assignment for cycle (N+1), or cycle_001 if nothing has run.
    """
    experiments = repo_root / "experiments"
    max_completed = 0
    for cycle_dir in sorted(experiments.glob("cycle_*")):
        if not cycle_dir.is_dir():
            continue
        review = cycle_dir / "impl_compare" / "comparison" / "review_decision.json"
        if review.is_file():
            num = int(cycle_dir.name.split("_")[1])
            if num > max_completed:
                max_completed = num

    if max_completed == 0:
        next_cycle = "cycle_001"
    else:
        next_cycle = f"cycle_{max_completed + 1:03d}"

    assignment = _assignment_path(repo_root, next_cycle)
    if assignment.is_file():
        _normalize_assignment_file(assignment)
        print(f"cycle_loop: auto-resume → {assignment.relative_to(repo_root)}")
    else:
        print(
            f"cycle_loop: auto-resume → {next_cycle} assignment not found, "
            f"creating via init_cycle.py"
        )
        # Bootstrap: run init_cycle to create the skeleton
        previous = f"cycle_{max_completed:03d}"
        subprocess.run(
            (
                sys.executable,
                "-B",
                "scripts/init_cycle.py",
                next_cycle,
                "--previous-cycle",
                previous,
                "--candidate-id",
                "candidate_001",
                "--agent-name",
                "flow_agent",
            ),
            cwd=repo_root,
            check=True,
        )
        # Patch the assignment with source_patch_mode
        _normalize_assignment_file(assignment)
    return assignment


def _review_exists(repo_root: Path, cycle_id: str) -> bool:
    return (
        repo_root
        / "experiments"
        / cycle_id
        / "impl_compare"
        / "comparison"
        / "review_decision.json"
    ).is_file()


def _assignment_path(repo_root: Path, cycle_id: str) -> Path:
    return (
        repo_root
        / "experiments"
        / cycle_id
        / "agents"
        / "assignments"
        / "candidate_001.json"
    )


def _next_assignment_path(repo_root: Path, next_cycle_id: str) -> Path | None:
    path = _assignment_path(repo_root, next_cycle_id)
    return path if path.is_file() else None


def _normalize_assignment_file(assignment_path: Path) -> None:
    """Ensure a Flow Agent assignment has self-consistent scope fields."""
    if not assignment_path.is_file():
        return
    payload = json.loads(assignment_path.read_text(encoding="utf-8"))
    normalized = normalize_flow_assignment_scope(payload)
    if normalized != payload:
        assignment_path.write_text(
            json.dumps(normalized, indent=2, sort_keys=True) + "\n",
            encoding="utf-8",
        )


def _increment_cycle_id(cycle_id: str) -> str:
    # cycle_NNN → cycle_(NNN+1)
    prefix, _, num = cycle_id.rpartition("_")
    return f"{prefix}_{int(num) + 1:0{len(num)}d}"


if __name__ == "__main__":
    raise SystemExit(main())
