"""Shared data shapes for the paper-style agent scaffold."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any, Mapping


TODO_DECISION = "TODO_DECISION"


@dataclass(frozen=True)
class AgentArtifactPaths:
    """Canonical artifact paths for one agent candidate."""

    plan: Path
    candidate_change: Path
    feedback: Path
    rule_update: Path

    def ensure_parent_dirs(self) -> None:
        for path in (self.plan, self.candidate_change, self.feedback, self.rule_update):
            path.parent.mkdir(parents=True, exist_ok=True)


@dataclass(frozen=True)
class AgentArtifacts:
    """Markdown artifacts produced by one agent run."""

    plan_markdown: str
    candidate_markdown: str
    feedback_markdown: str
    rule_update_markdown: str
    decision: str = TODO_DECISION


@dataclass(frozen=True)
class CandidateFlow:
    """A proposed ABC command flow generated by an LLM agent."""

    commands: tuple[str, ...]
    rationale: str
    source_design: str = "TODO_SOURCE_DESIGN"
    expected_effect: str = "TODO_EXPECTED_EFFECT"
    risk_notes: tuple[str, ...] = ()
    validation_plan: tuple[str, ...] = ()

    def to_abc_script(self) -> str:
        normalized = [command.strip().rstrip(";") for command in self.commands]
        normalized = [command for command in normalized if command]
        return ";\n".join(normalized) + ";\n"


@dataclass(frozen=True)
class ParsedAgentResponse:
    """Structured model output after schema validation.

    TODO_PARSE_MODEL_JSON: Replace this placeholder with a strict parser for the
    exact JSON schema expected from the selected model.
    """

    raw: Mapping[str, Any]
    plan_items: tuple[str, ...]
    candidate_flow: CandidateFlow | None
    risks: tuple[str, ...]
    rule_updates: tuple[str, ...]
    decision: str


def markdown_bullets(items: tuple[str, ...] | list[str]) -> str:
    if not items:
        return "- TODO_EMPTY_LIST\n"
    return "\n".join(f"- {item}" for item in items) + "\n"

